version: '3.3'

services:
  web:
    build: ./backend
    container_name: usersRestAPI01
    # command: bash -c "export API_AUTHENTICATION="False" && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn usersRestAPI.wsgi -b 0.0.0.0:8000 && python3 manage.py collectstatic --noinput"
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./backend/:/src
    ports:
      - "8000:8000"
    
  db:
    image: postgres:latest
    container_name: postgres01 
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust