version: '3.3'

services:
  web:
    build: ./backend
    container_name: usersRestAPI01
    # command: bash -c "export API_AUTHENTICATION="False" && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn usersRestAPI.wsgi -b 0.0.0.0:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    volumes:
      - ./backend/:/backend
    ports:
      - "8000:8000"
    
  db:
    image: postgres:latest
    container_name: postgres01
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # vue:
  #   build: ./frontend/vue
  #   container_name: vue_container
  #   ports:
  #     - "8080:8080"
  #   command: npm start
  #   volumes:
  #     - "./frontend/vue:/frontend/vue"

